server:
  port: 8081

spring:
  application:
    name: activiti-with-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti5?autoReconnect=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sa123;
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
